### ISSUE TITLE
Morning session: Peer-to-peer code review

### ISSUE THREAD

**Issue by didierganthier** [kal2944/Awesome-books-with-ES6#2]
Hi @kal2944 ,
Your project is complete!  You did a great work... Congratulations 🥳 
Congratulations! 🎉 

<img src="https://media.giphy.com/media/ytTYwIlbD1FBu/giphy.gif"/>

## Highlights

- You have added a descriptive Readme file. Good Job. ✔️ 
- There is no linter error present. ✔️ 
- Love the fonts and the design. ✔️ 
- The project has met all the technical aspects you needed for this project. Keep rocking! ✔️ 

## Optional suggestions
However, there's always room for improvement...
I noticed that you use `add` and `remove`. In order to follow Javascript best practices, make the code DRY and improve readability, you should use `toggle` in the following lines:
https://github.com/kal2944/Awesome-books-with-ES6/blob/717983cc3565c5cc92392a9b32ee2bc93d50e092/index.js#L19-L38

Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

**Comment by kal2944** [comment]
Thank you for your comment and recommendation, I will look through it!
